# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Call Me Out' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Call Me Out
  pod 'BABCropperView'
  pod 'ActionSheetPicker-3.0'
#  pod 'AXRatingView'
  pod 'AlamofireImage'
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'ProgressHUD'
  pod 'Toast-Swift'
  pod "Player"
#  pod 'HCSStarRatingView'
  pod 'TagListView'
  pod 'ImageSlideshow'
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleSignIn'
  
  pod 'Cache'
#  pod 'VGPlayer', '~> 0.2.0'

  pod 'Google-Mobile-Ads-SDK'
  pod 'CRRefresh'
  
  pod 'SDWebImage', '~> 4.- '
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
end
